### ISSUE TITLE
Error running 3.0.1 (not present in 2.0.1)

### ISSUE THREAD

**Issue by cruzerld** [felixrieseberg/electron-windows-notifications#10]
I'm getting the following error when trying to run 3.0.1:

App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
...\node_modules\@nodert-win10-cu\windows.ui.notifications\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\node_modules\@nodert-win10-cu\windows.ui.notifications\lib\main.js:25:20)
    at Object.<anonymous> (...\node_modules\@nodert-win10-cu\windows.ui.notifications\lib\main.js:69:3)

Note that everything builds correctly and that 2.0.1 links correctly.

I anonymized the paths, so ignore the '...'

**Comment by genbtc** [comment]
I'm getting this error too on Win 1803 x64 + Version 3.0.1 . The npm compile failed with some errors and I also cannot compile 2.01 or 2.1.1, comes up with a lot more errors, Its almost like I'm missing a bunch of the windows.ui.notifications dependences or somethin.. This is on a system with most MSVC's installed

**Comment by mkgareja** [comment]
getting the same error. Please let me know if there is any workaround?
