### ISSUE TITLE
Can't install with yarn or npm

### ISSUE THREAD

**Issue by mrbuds** [felixrieseberg/electron-windows-notifications#11]
```
C:\Users\buds\Documents\GitHub\wa-update\node_modules\@nodert-win10-cu\windows.applicationmodel>if not defined npm_config_node_gyp (node "C:\Users\buds\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\buds\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\buds\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\buds\Documents\GitHub\wa-update\node_modules\@nodert-win10-cu\windows.applicationmodel
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN weakauras-wago-updater@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodert-win10-cu/windows.applicationmodel@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodert-win10-cu/windows.applicationmodel@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\buds\AppData\Roaming\npm-cache\_logs\2018-11-26T04_51_08_581Z-debug.log

```

I have a working python installed in this directory, but anyway that's kinda weird to ask for python on a npm module

**Comment by TwistedJester1** [comment]
I got the same issue. Pretty sure it's on the person's end rather than a issue of how we have it setup. Hopefully they fix it.

**Comment by Frankobingen** [comment]
Same error

**Comment by lengthmin** [comment]
please see this issue's reason: https://github.com/NodeRT/NodeRT/issues/65#issuecomment-303938757

and a workaround: https://github.com/NodeRT/NodeRT/issues/65#issuecomment-304010018
