### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by TwistedJester1** [felixrieseberg/electron-windows-notifications#14]
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Abyss Watcher\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Abyss Watcher\source\repos\TheWatcher\TheWatcher\node_modules\@nodert-win10-cu\windows.applicationmodel
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN the-watcher@0.0.0 No repository field.
npm WARN the-watcher@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodert-win10-cu/windows.applicationmodel@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodert-win10-cu/windows.applicationmodel@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abyss Watcher\AppData\Roaming\npm-cache\_logs\2019-03-17T18_02_55_302Z-debug.log
```

**Comment by Crewski** [comment]
Same issue for me

**Comment by eluchsinger** [comment]
Same

**Comment by Un-knownCoder** [comment]
In my case it says that I have to set an Environmental Variable... but, after i set the variable, it still throw the same error 🤕😫

**Comment by GioPan04** [comment]
Same 😰😭

**Comment by Un-knownCoder** [comment]
Finally I found a solution... Well, I know that it doesn't fix the problem, but it just do the same thing... I'm talking about the npm module: **node-notifier** - https://www.npmjs.com/package/node-notifier <br> *(and it works even in other OS)*

> **P.S.**: in Windows (under the notification body) It shows an app id (Snore Toast), but I don't know how to remove it...

**Comment by GioPan04** [comment]
@Un-knownCoder Ok thanks. I will try it :smile:

**Comment by Un-knownCoder** [comment]
Unfortunately that code string doesn't work... It's because the notificaton is called from an external executable with a different app id

**Comment by Stanzilla** [comment]
node-gyp does not work with Python 3, you need Python 2

**Comment by CaiqueCassemiro** [comment]
the same for me

**Comment by geoctrl** [comment]
I have python 2.7.15 installed and i'm still getting errors installing 🤷‍♀

**Comment by Stanzilla** [comment]
@geoctrl you'd have to post your errors
