### ISSUE TITLE
does not allow me to run npm install

### ISSUE THREAD

**Issue by Praveer1981** [felixrieseberg/electron-windows-notifications#20]
G:\Github_Downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel>if not defined npm_config_node_gyp (node "C:\Users\kumarpr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kumarpr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
g:\github_downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\_nodert_generated.cpp : fatal error C1107: could not fi
nd assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [G:\Github_Downloads\electron-wind
ows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
g:\github_downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\nodertutils.cpp : fatal error C1107: could not find ass
embly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [G:\Github_Downloads\electron-windows-no
tifications\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
g:\github_downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\opaquewrapper.cpp : fatal error C1107: could not find a
ssembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [G:\Github_Downloads\electron-windows-
notifications\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
g:\github_downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\collectionsconverterutils.cpp : fatal error C1107: coul
d not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [G:\Github_Downloads\elect
ron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
  win_delay_load_hook.cc
c:\users\kumarpr\appdata\roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'platform.win
md': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [G:\Github_Downloads\electron-windows-notifications\node_mo
dules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kumarpr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kumarpr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\Github_Downloads\electron-windows-notifications\node_modules\@nodert-win10-au\windows.applicationmodel
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE

**Comment by Praveer1981** [comment]
@felixrieseberg

**Comment by sukolenvo** [comment]
Same for me

**Comment by whizdummy** [comment]
I fixed the same error it by doing the following steps:
1) Download Windows SDK first. I downloaded this version: https://go.microsoft.com/fwlink/p/?LinkId=838916 to match the [NodeRT](https://github.com/nodert/nodert) version this library is using (nodert-win10-au).
2) Follow additional steps indicated here: https://stackoverflow.com/questions/42157554/nodert-could-not-find-assembly/54591996#54591996.
3) Run _npm install_ again.

Your app will now run.

Hope it helps.
