### ISSUE TITLE
uncaughtException: The specified module could not be found.

### ISSUE THREAD

**Issue by adids93** [felixrieseberg/electron-windows-notifications#22]
I am facing the below exception when I try to load the electron-windows-notification module only on a few machines(a windows laptop and a windows 10 VM). Works fine on the rest of the machines. I are using electron-builder to build the app.

Error stack:

uncaughtException: The specified module could not be found.
\\?\C:\Users\IEUser\AppData\Local\Temp\49aaf4c2-8efb-4642-9d5d-b9cde8c781ac.tmp.node
Error: The specified module could not be found.
\\?\C:\Users\IEUser\AppData\Local\Temp\49aaf4c2-8efb-4642-9d5d-b9cde8c781ac.tmp.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Program Files (x86)\iTutor2\dist\browser\resources\app.asar\node_modules\@nodert-win10-au\windows.ui.notifications\lib\main.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Program Files (x86)\iTutor2\dist\browser\resources\app.asar\node_modules\electron-windows-notifications\src\index.js:33:27)
    at Module._compile (internal/modules/cjs/loader.js:880:30)

I have tried the below solutions to fix the issue, but none of them have worked.

1. Used dependency walker on the .tmp.node module and copied few missing dlls (vcruntime140.dll, vccorlib140.dll, msvcp140.dll) from system32 directory to the root directory of the app.

2. Unpacked the module from asar

**Comment by eternalharvest** [comment]
@adids93 

I had same issue, but in my case when i install the latest visual c++ runtime below, the problem was gone.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by OFMaurice** [comment]
Is there a way to embed this to to packaged app so that the user doesnt have to install the runtime?
