### ISSUE TITLE
Example in readme throw error 

### ISSUE THREAD

**Issue by zalewskigrzegorz** [felixrieseberg/electron-windows-notifications#9]
I got an error after using example from readme
```
Uncaught (in promise) Error: Cannot find module '@nodert-win10-au/windows.ui.notifications'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\code\xxx\xxx\node_modules\electron-prebuilt-compile\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\code\xxx\xxx\node_modules\electron-windows-notifications\src\index.js:33:27)
    at Object.<anonymous> (C:\code\xxx\xxx\node_modules\electron-windows-notifications\src\index.js:47:3)
    at Module._compile (module.js:569:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\code\xxx\xxx\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at ProxyComponent.App (C:\code\xxx\xxx\src\app.jsx:151:35)
    at App (eval at <anonymous> (C:\code\xxx\xxx\node_modules\react-hot-loader\dist\react-hot-loader.development.js:225:54), <anonymous>:5:7)
    at C:\code\xxx\xxx\node_modules\react-dom\lib\ReactCompositeComponent.js:292:18
    at measureLifeCyclePerf (C:\code\xxx\xxx\node_modules\react-dom\lib\ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (C:\code\xxx\xxx\node_modules\react-dom\lib\ReactCompositeComponent.js:291:16)
    at ReactCompositeComponentWrapper._constructComponent (C:\code\xxx\xxx\node_modules\react-dom\lib\ReactCompositeComponent.js:282:19)
    at ReactCompositeComponentWrapper.mountComponent (C:\code\xxx\xxx\node_modules\react-dom\lib\ReactCompositeComponent.js:185:21)
    at Object.mountComponent (C:\code\xxx\xxx\node_modules\react-dom\lib\ReactReconciler.js:43:35)
```
if @nodert-win10-au/windows.ui.notifications is required should be included in dependency.

**Comment by zalewskigrzegorz** [comment]
I'm closing this issue due to inactivity. If further assistance is needed, please feel free to reopen or create a new.
